### ISSUE TITLE
old dirs not cleaning  up

### ISSUE THREAD

**Issue by ChillarAnand** [zonkyy/helm-dired-recent-dirs#5]
If i delete  a file and run `recentf-cleanup`, it will remove that file from recentf list. 

If i move a dir from one location to another location, it  is better if this package  can cleanup up invalid dirs also.

**Comment by zonkyy** [comment]
This package doesn't use recentf, so you can't use `recentf-cleanup`.

Please edit `~/.chpwd-recent-dirs`.
