### ISSUE TITLE
Support fish shell

### ISSUE THREAD

**Issue by swarnendubiswas** [zonkyy/helm-dired-recent-dirs#6]
Fish shell has a slightly different syntax, and does not support &&. So helm-dired-recent-dirs source fails if we have fish set as the default shell. Is it possible to include fish as a possible shell type and issue a different fish shell compatible command? Fish shell is pretty convenient to use.

**Comment by zonkyy** [comment]
Helm-dired-recent-dirs does not support fish shell.
If you use z plugin (https://github.com/fisherman/z), you can use helm-z (https://github.com/yynozk/helm-z).
